### ISSUE TITLE
setServerUrl breaks compatibility with some endpoints

### ISSUE THREAD

**Issue by scsouthw** [Microsoft/ApplicationInsights-iOS#108]
we should remove this check: https://github.com/Microsoft/ApplicationInsights-iOS/blob/a306f26118c39291f097b395c216772d0710e6ef/Classes/MSAIApplicationInsights.m#L246-L249

and change this so that it doesn't cause a trailing slash to be appended to the endpoint of the path is nil: https://github.com/Microsoft/ApplicationInsights-iOS/blob/a306f26118c39291f097b395c216772d0710e6ef/Classes/MSAIAppClient.m#L24

**Comment by lumaxis** [comment]
Adding some more info: Apparently some endpoints can't handle that we always enforce the existence of a trailing slash so we might overthink that logic
