### ISSUE TITLE
Handled exceptions are always sent as crashes and not as handled exceptions

### ISSUE THREAD

**Issue by ryanholden8** [Microsoft/ApplicationInsights-iOS#112]
I have this code:

```objc
@try {
    @throw [[NSException alloc] initWithName:@"test" reason:@"reason"];
} @catch (NSException *exception) {
    [MSAITelemetryManager trackException:exception];
}
```

This is tracked as a crash in the portal, but it's a handled exception.

Taking a look at the source code shows all exceptions go through the crash reporting process, regardless of handled or not. - https://github.com/Microsoft/ApplicationInsights-iOS/blob/master/Classes/MSAITelemetryManager.m#L239-L254

Until this is handled I guess the workaround would be to use traceMessage with custom properties?

**Comment by lumaxis** [comment]
Hi Ryan,
while we're investigating how we can support handled exceptions better in the future, let me just add a general remark on exceptions in Cocoa/Cocoa Touch. Quoting an [official Apple guide] ():

>**Signaling Errors**
>Although exceptions are commonly used in many programming environments to control programming flow or to signify errors, do not use exceptions in this way in Cocoa and Cocoa Touch applications. Instead, you should use the return value of a method or function to indicate that an error has occurred, and provide information about the problem in an error object. For more information, see [Error Handling Programming Guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/ErrorHandling/ErrorHandling.html#//apple_ref/doc/uid/TP40001806).

It is very important to understand that error handling on iOS, in contrast to for example Java, does not at all rely on exceptions in a way that you may be used to.
Thanks for writing in and be sure to let us know if you have any more questions or run into any issues!

**Comment by ryanholden8** [comment]
Hi Lukas,

Thank you for the response, I appreciate it!

True, but as with the example code above, I'm generating a exception object specifically for the purpose of sending a handled exception to Application Insights.

Is there a way I can send a NSError Object? That's the original object I'm dealing with, not a exception. Or is safe to say that handled exceptions are not supported by Application Insights for iOS at the present time?

Again, thank you for your time! :)

**Comment by lumaxis** [comment]
Hey @ryanholden8, sorry it took so long to get back to you with a response! Unfortunately, currently the only way to send an NSError is tracking a custom event with the error description as a message. Although we are thinking about a long-term solution for how to handle general errors, you might be happy to here that we're currently working on better supporting exceptions too. This might still be a few weeks out though. Thanks again for sharing your feedback, feel free to send anything you have on your mind in the future!
