### ISSUE TITLE
Rebuild with bit code enabled

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/ApplicationInsights-iOS#120]
Building with the latest Xcode 7.0 beta 6 (7A192o), I get the following error about the framework not being built with bit code.

I am including the framework via Cocoapods and am include 1.0-beta.6 of the App insights iOS framework.

ApplicationInsights/ApplicationInsights/ApplicationInsights.framework/ApplicationInsights(MSAIApplicationInsights.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ryanholden8** [comment]
I too am hoping we can use bit code. Any ETA on this?

**Comment by lumaxis** [comment]
Sorry guys, we have currently no ETA for supporting Bitcode.
You're of course always free to integrate the SDK as source and rebuild with Bitcode yourself.
