### ISSUE TITLE
Ability to flush the current dataitem queue from MSAIChannel

### ISSUE THREAD

**Issue by arazuvaev** [Microsoft/ApplicationInsights-iOS#123]
Is there any way to force a flush on MSAIChannel queue, before the senderinterval time?
To clarify, we'd have to be able to do it from MSAITelemetryManager

**Comment by chrwend** [comment]
Hi,

currently we don't offer a way to flush the channel queue. Feel free to tweak the code as you like. This is what you are looking for: (https://github.com/Microsoft/ApplicationInsights-iOS/blob/master/Classes/MSAIChannelPrivate.h#L60)[https://github.com/Microsoft/ApplicationInsights-iOS/blob/master/Classes/MSAIChannelPrivate.h#L60]

Best,

Chris
