### ISSUE TITLE
Improve error reporting and alerting

### ISSUE THREAD

**Issue by bbowers0** [Microsoft/ApplicationInsights-iOS#124]
If you want to get alerted by Application Insights when an error occurs in an iOS app, you have to use the trackException method.  This shows up in the portal as a "crash", but it manifests as the "Server exceptions" metric in the alert rules.   The trackException method does not allow you to include a properties dictionary, so then you have to send an additional trackTraceWithMessage:properties: or trackEventWithName:properties: call to send additional property information (the TrackException method in the .NET API does allow you to send additional properties and metrics).  This seems very unpolished, especially since the use of exceptions in iOS isn't standard.

**Comment by ashtom** [comment]
We have currently no plans to extend the SDK's API or the backend's alerting mechanism.
