### ISSUE TITLE
Generate test crash wiki out of date

### ISSUE THREAD

**Issue by mannix** [Microsoft/ApplicationInsights-iOS#128]
On this wiki page:
https://github.com/Microsoft/ApplicationInsights-iOS/wiki/How-to-Generate-a-Test-Crash

The code snippet for triggering a crash is out of date. Instead of:
```objc
[[[MSAIApplicationInsights sharedInstance] crashManager] generateTestCrash];
```
It should be\*
```objc
[[MSAICrashManager sharedManager] generateTestCrash];
```

\* I haven't actually tested this in objc. I'm writing mine in Swift and this worked for me:
```swift
MSAICrashManager.sharedManager().generateTestCrash()
```

**Comment by lumaxis** [comment]
You're absolutely right. Fixed, thanks! :+1:
