### ISSUE TITLE
Duplicate symbols when using with HockeyApp

### ISSUE THREAD

**Issue by JessicaYeh** [Microsoft/ApplicationInsights-iOS#134]
Hello! I tried again to use App Insights (beta 7) with HockeyApp (preseason) and I'm getting some duplicate symbol errors when I build the project:

    duplicate symbol _defaultFileCount in:
        /Users/jessicayeh/Documents/OmniBuzz/iOS and Apple Watch/Vendor/ApplicationInsights/ApplicationInsights.framework/ApplicationInsights(MSAIPersistence.o)
        /Users/jessicayeh/Documents/OmniBuzz/iOS and Apple Watch/Vendor/HockeySDK.embeddedframework/HockeySDK.framework/HockeySDK(BITPersistence.o)
    duplicate symbol _kPersistenceQueueString in:
        /Users/jessicayeh/Documents/OmniBuzz/iOS and Apple Watch/Vendor/ApplicationInsights/ApplicationInsights.framework/ApplicationInsights(MSAIPersistence.o)
        /Users/jessicayeh/Documents/OmniBuzz/iOS and Apple Watch/Vendor/HockeySDK.embeddedframework/HockeySDK.framework/HockeySDK(BITPersistence.o)
    duplicate symbol _kFileBaseString in:
        /Users/jessicayeh/Documents/OmniBuzz/iOS and Apple Watch/Vendor/ApplicationInsights/ApplicationInsights.framework/ApplicationInsights(MSAIPersistence.o)
        /Users/jessicayeh/Documents/OmniBuzz/iOS and Apple Watch/Vendor/HockeySDK.embeddedframework/HockeySDK.framework/HockeySDK(BITPersistence.o)
    ld: 3 duplicate symbols for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

I also cleaned the project and deleted derived data.

**Comment by lumaxis** [comment]
Thanks! We'll fix this with the next Preseason release :)
