### ISSUE TITLE
Many warnings after archiving (but not after building)

### ISSUE THREAD

**Issue by JessicaYeh** [Microsoft/ApplicationInsights-iOS#135]
When I archive my project to submit to the app store, I get a crazy amount of warnings (200+) from App Insights 😯 It's only when I archive, when I just build it, the warnings don't show up.

![image](https://cloud.githubusercontent.com/assets/3309218/13578518/12326770-e45e-11e5-9e0c-b5a52b3f41a3.png)

![image](https://cloud.githubusercontent.com/assets/3309218/13578492/e67b881e-e45d-11e5-97c6-afbad93bae76.png)

Here's a similar problem on the Apple Developer forums: https://forums.developer.apple.com/thread/17921

**Comment by lumaxis** [comment]
This is most probably an issue with Xcode but not really something to worry about. Fixed with the updated binary.
