### ISSUE TITLE
No time between sessions data shows up in portal

### ISSUE THREAD

**Issue by yunzhouMSFT** [Microsoft/ApplicationInsights-iOS#15]
No time between sessions data shows up. 
o	How do we calculate this? Are we doing the right thing for iOS apps?
o	Didn’t see data, even after multiple sessions and waiting for a while

**Comment by lukasspiess** [comment]
Currently, sessions are renewed after each complete restart of the app (i.e. when the app is loaded to memory) and after the app has been in the background for at least 20 seconds. Session renewal entails a new session ID and the `isNew` flag being set to `true` for the first data item in that session. 
We will probably start instrumenting the new `sessionState` data type in the future.

**Comment by lukasspiess** [comment]
Verified that everything works as expected, closing.
