### ISSUE TITLE
The 1.0-beta.3 release zip doesn't match source code

### ISSUE THREAD

**Issue by dtweston** [Microsoft/ApplicationInsights-iOS#82]
This seems to be an odd problem. The 1.0-beta.3 release zip still has the MSAICrashMetaData.h file included within it, but that file is not imported in the ApplicationInsights.h umbrella header, so the module fails to compile in Xcode. If I add `#import "MSAICrashMetaData.h" to the umbrella header, everything seems to compile correctly.

However, when I look at the git repo, this file has been removed from the latest release. Is this a bad release binary?

**Comment by lukasspiess** [comment]
This apparently was indeed a caching issue in our release process where the unnecessary `MSAICrashMetaData.h` file was not properly removed from the build product.
I just uploaded a fixes binary which should solve the issue. 
@dtweston Could you please simply redownload from the releases tab and try again with the new binary? Thanks!

**Comment by dtweston** [comment]
Thanks, the new binary has fixed this issue. I had to delete the cached version at ~/Library/Caches/CocoaPods/Pods/Release/ApplicationInsights and I haven't quite gotten it to work as a pod yet, but I'm making progress. Thanks!

**Comment by lukasspiess** [comment]
@dtweston I'll close this for now since it seems to work for you now. Please don't hesitate to get back to us in case anything isn't working or you have any questions. Thanks again!

**Comment by dtweston** [comment]
Thanks @lukasspiess, I am just coming back to this again, at it is working. It even seems to be working for me as a dependency of another project, which I didn't think was supported by Cocoapods.
