### ISSUE TITLE
Pod

### ISSUE THREAD

**Issue by LOVE2CODE123** [Microsoft/ApplicationInsights-iOS#86]
Could this be made into a pod?

**Comment by lukasspiess** [comment]
This SDK is already available on CocoaPods: https://cocoapods.org/?q=applicationinsights

**Comment by LOVE2CODE123** [comment]
Fantastic, I must of types something wrong when I searched for it.

**Comment by lukasspiess** [comment]
Sure, no problem! Be sure to let us know if you run into any problems or have any more questions :)
